// Roll: 1703016

// Consider given code, #include<math.h> int main(){ float a=1; float b=2; float c=a+b; return 0; } . Show output file with extension ".i" generated by C compiler along with Makefile (point penalty for adding extra commands other than necessary).

#include<math.h> 
int main(){ 
   float a=1; float b=2; float c=a+b; 
   return 0; 
}