// Roll: 1703016

/* Problem 1: Show output files of all stages along with dumped object file generated by C compiler along with Makefile */


#include<math.h> 
#define INTEGER int 

int main() 
{ 
   INTEGER a=10; 
   INTEGER b=20;
   return 0;
} 